#!/usr/bin/env bash
set -euo pipefail

CONTENT_DIR="${CONTENT_DIR:-content/projects}"
OUTPUT_FILE="${OUTPUT_FILE:-data/projects.yaml}"

repos=$(grep -hoE '^repo = "[^"]+"' "$CONTENT_DIR"/*.md | sed -E 's/^repo = "(.*)"$/\1/')

{
  printf '# Auto-generated by scripts/fetch-projects.sh — do not edit manually\n\n'
  for url in $repos; do
    owner_repo="${url#https://github.com/}"
    owner_repo="${owner_repo%/}"

    response=$(curl -sf \
      -H "Authorization: Bearer ${GITHUB_TOKEN}" \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/${owner_repo}")

    echo "$response" | jq -r --arg url "$url" '
      def quote: "\"" + gsub("\""; "\\\"") + "\"";
      ($url | quote) + ":",
      "  name: " + (.name | quote),
      "  description: " + ((.description // "No description provided") | quote),
      "  language: " + ((.language // "") | quote),
      ""
    '
  done
} > "$OUTPUT_FILE"

count=$(echo "$repos" | grep -c . || true)
echo "Wrote $count projects to $OUTPUT_FILE"
