#!/usr/bin/env bash
set -euo pipefail

CONTENT_DIR="${CONTENT_DIR:-content/music}"
OUTPUT_FILE="${OUTPUT_FILE:-data/music.yaml}"

urls=$(grep -hoE '^track = "[^"]+"' "$CONTENT_DIR"/*.md 2>/dev/null | sed -E 's/^track = "(.*)"$/\1/' || true)

{
  printf '# Auto-generated by scripts/fetch-music.sh — do not edit manually\n\n'
  for url in $urls; do
    response=$(curl -sf --get "https://soundcloud.com/oembed" \
      --data-urlencode "url=${url}" \
      --data-urlencode "format=json")

    echo "$response" | jq -r --arg url "$url" '
      def quote: "\"" + gsub("\""; "\\\"") + "\"";
      ($url | quote) + ":",
      "  title: " + ((.title // "Untitled") | quote),
      "  description: " + ((.description // "") | quote),
      "  thumbnail_url: " + ((.thumbnail_url // "") | quote),
      ""
    '
  done
} > "$OUTPUT_FILE"

count=$(echo "$urls" | grep -c . || true)
echo "Wrote $count tracks to $OUTPUT_FILE"
